"""Shared Matplotlib style for the figures generated by this package.

Central place for the figure conventions (fonts, grid, line widths), the
visual identity of the flagship controllers and the PNG export settings, so
every committed asset looks like one family. Plotting helpers call
``apply_style`` before drawing and export through ``save_figure``.

``apply_style`` updates Matplotlib's global rcParams on purpose (the library
is figure-producing, not figure-styling-on-demand); it is idempotent and
applied per figure so outputs do not depend on the caller's state.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt

__all__ = [
    "CONTROLLER_STYLES",
    "DOUBLE_SIZE",
    "FIGURE_DPI",
    "SINGLE_SIZE",
    "apply_style",
    "save_figure",
]

# Visual identity of the flagship controllers: one label and one colour used
# by every figure, table and animation, so a controller always looks the same
# across assets. Keys are the component IDs from vessel_gnc.reference.
CONTROLLER_STYLES: dict[str, dict[str, str]] = {
    "los_pid_v1": {"label": "LOS", "color": "0.45"},
    "nominal_nmpc_v1": {"label": "nominal NMPC", "color": "tab:blue"},
    "disturbance_aware_nmpc_v1": {"label": "aware NMPC", "color": "tab:green"},
    "disturbance_aware_mpcc_v1": {"label": "geometric MPCC", "color": "tab:purple"},
}

SINGLE_SIZE = (7.2, 6.4)  # [in] one-panel figures
DOUBLE_SIZE = (11.5, 8.2)  # [in] comparison figures
FIGURE_DPI = 200  # PNG export resolution for the committed assets


def apply_style() -> None:
    """Apply the package figure style (idempotent)."""
    mpl.rcParams.update(
        {
            "axes.grid": True,
            "grid.alpha": 0.3,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 8.5,
            "legend.framealpha": 0.9,
            "lines.linewidth": 1.3,
        }
    )


def save_figure(fig: plt.Figure, output_path: str | Path) -> None:
    """Save a figure as PNG at the package DPI, creating parent directories.

    Args:
        fig: the Matplotlib figure to export.
        output_path: destination path; parents are created as needed.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=FIGURE_DPI, bbox_inches="tight")
